language: node_js
node_js:
  - 4
  - 5
  - 6

notifications:
  slack:
    - secure: "EH0hBkyAqwka7w4sWHhJi19gBgnLD26nKjCcmgzmWBPURqq9PQHkAE6jRNfnqdIeRUZsQZLEnhVHI4yf4Cl8+Nf8MZVZTP3ys+yIUmnp/6zmE+ncrzbMUu+urCinycxcUKQpOPfaU5MK/e/iA/IjPWg4/AxxPaIeI0mGD7hGSdvysR13MvXxEw2croORgcIC/hgo0NIOYmwyF6+rz3kyFmSF/Qqezu3VJ0T6fZp+wlgamj2Wkluj7FNTdSubsLANT769N7c4CCWGDU/VrS64nfqqiDbPpI5onjsucocejiVElkXPl8ZkxwLRzejRrXLbuTdFys9PDxdm8ZwF82OjS8mxq8b+ibg7lObiFYBGpTTHZhDyc6BKgLJlXQ21zjENxUiuU48y0sNZ4JHyTQ/JzpVzR/LTruUVo1xWm50hK1755SA5nvfYRCJjpJj4mXEk/0uxBxyuDy7WTt+mquCTs6ty2E2MkpoXArOWGkW6JJDaNsQLn7vbkFSBwVDpnT7O2qRpRxNXAGF4Io0hS3g0k4AHrvKgzq6S3+vjtr5GxIjNB6Um6XCFRIqbzO0R/rE0yuMG1VG5NwAonyxxC3faD0giA3dSjOebmVQzyHPy16aV4QDCFo9e3fRg+U4aYR9CTftsaCifDurKaNHhagMPsCAf1A1lotCp5rFhJA4ByE8="
